name: QA Env Run alchemy only test cases ALC-4363, ALC-4362, ALC-666, ALC-4356, ALC-4355, ALC-4353

on:
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: 'x64'
        cache: 'maven'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1' # Specify Node.js version

    - name: Install npm version 9.4.2
      run: |
        npm install -g npm@9.4.2

    - name: Install Newman version 5.3.2
      run: |
        npm install -g newman@5.3.2

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom-alchemy.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Install Maven dependencies
      run: mvn -f pom-alchemy.xml install

    - name: Get Latest Build ID
      id: get_build_id
      shell: pwsh
      continue-on-error: true
      run: |
        $response = Invoke-RestMethod -Uri "https://api.lambdatest.com/automation/api/v1/builds?limit=1" -Method Get -Headers @{
          Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('ashish.rawatfleekitsolutions:MWAa6go8FynMFZt5GYZyeKtSycfc6I2YKQhFn1PH2h1Tw6Syo2')))"
        }
        $build_id = $response.data[0].build_id
        Write-Host "Build ID: $build_id"
        echo "BUILD_ID=$build_id" >> $env:GITHUB_ENV

    - name: Generate Shareable Link
      id: generate_shareable_link
      shell: pwsh
      continue-on-error: true
      run: |
        $build_id = $env:BUILD_ID
        $requestBody = @{
          expiresAt = 3
          themeVersion = "v2"
          isThemeEnabled = $true
          entityType = "Automation Build"
          entityIds = @($build_id)
        } | ConvertTo-Json -Compress
        $response = Invoke-RestMethod -Uri "https://api.lambdatest.com/lshs/api/v1.0/share-item/generate-sharable-link" -Method Post -Headers @{
          Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('ashish.rawatfleekitsolutions:MWAa6go8FynMFZt5GYZyeKtSycfc6I2YKQhFn1PH2h1Tw6Syo2')))"
          'Content-Type' = 'application/json'
        } -Body $requestBody
        $shareUrl = $response.shareIdUrl
        Write-Host "Shareable Report URL: $shareUrl"
        echo "SHAREABLE_URL=$shareUrl" >> $env:GITHUB_ENV

    - name: Send Notification to Slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SHAREABLE_URL: ${{ env.SHAREABLE_URL }}
        continue-on-error: true
      run: |
        $headers = @{
          'Content-Type' = 'application/json'
        }
        $body = @{
          text = "QA Env Alchemy only Test Cases Automated Execution Completed. Open this link to check the report: $env:SHAREABLE_URL"
        } | ConvertTo-Json
        Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
